### PR TITLE
1st pull request

### PR DESCRIPTION
**Pull request by Darkusmaley**
I messed up on the pull request and I am not sure how to rectify it. It's supposed to be stag-react-api compared to main.

### CODE REVIEW

**Comment by FiLLa-FaS** [comment]
Hello! Thanks for sending your project for review, your project already looks pretty good! I marked several comments below and hope that they can help you to improve your project and get more final points. Good luck!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Mismatches of the main page on 1440px https://pasteboard.co/3GCYEQpoEIyO.png https://pasteboard.co/Jrbwutp16pYc.png
    * Mismatches of the main page on 768px https://pasteboard.co/nSGnw4qLaWED.png https://pasteboard.co/QqdC5fE0fRsf.png https://pasteboard.co/3KRombqprZqo.png
    * Mismatches of the main page on 320px https://pasteboard.co/GqbeVg7PdFTR.png https://pasteboard.co/Wsz90ydtK8WY.png https://pasteboard.co/BGstc4mHJ7G0.png
    * Background image for header and search form should keep its size on mobile screen resolutions
    * Incorrect text properties of all elements inside the modal window
    * Incorrect color of the modal submit button
    * Incorrect height of the modal window on 320 viewport
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * There's horizontal scrolling on more than 1000px (please note, that we should check the scroll without device toolvar on bigger screen resolutions)
    * There's horizontal scrolling of the home page on 767px - 930px screen resolutions
    * Footer shouldn't overlap the about section on mobile screen resolutions
    * All page content should be centered horizontally on all screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * Please don't use capital letters in class names throughout the project
    * BEM elements shouldn't be used outside their blocks, for example `home__grouping` shouldn't be used outside the `home` block. Please fix similar cases **throughout the project**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
      * You should have separate css file for all fonts imports - each font-face should have its own `@font-face` rule with properties and import
- [x]  There are no linting errors or warnings.
    * The project has several eslint warnings

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * All buttons should have pointer cursor
    * Modal submit button looks different from the mockup
    * Header tabs shouldn't change its color on hover state
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have at least two values with at least one alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 58

**Comment by FiLLa-FaS** [comment]
Hey! Thanks for the corrections, your project looks better! Several small issues in the code and below are left:⏬

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Header and search form background image looks darker than it should be
    * Most of the text elements have incorrect fonts, you need to make sure that all necessary fonts are added to the project and linked correctly and all `font-family` styles are written properly
    * Incorrect space between the start of the page and modal window on 320 viewport
    * Incorrect width of the `modal__title`
    * Mismatches of the home page on 1440px https://pasteboard.co/fl6LrewAsDu8.png
    * Mismatches of the home page on 768px https://pasteboard.co/VCaXztJPTCfb.png https://pasteboard.co/yveb4iKtnJqh.png https://pasteboard.co/JDVN6VEXQYrE.png
    * Mismatches of the home page on 320px https://pasteboard.co/jeeDeriG9mMB.png https://pasteboard.co/V0HrtgAI68Qm.png https://pasteboard.co/qzdDXg9GQ7Qu.png
    * Incorrect space between the `about` and footer sections on 320 and 768 viewports
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * `form__input` shouldn't extend outside the modal window on intermediate screen resolutions
    * Modal window should grow with changing the screen width on intermediate screen resolutions and should be centered on all screen resolutions
    * All pages content should be centered horizontally on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
    * Please don't use capital letters in class names throughout the project (there's `App` class in the project)
    * `header__link_grouping` should be a BEM element
    * BEM elements shouldn't be used outside their blocks, for example `news-card__list` shouldn't be used outside the `news-card` block. Please fix similar cases **throughout the project**
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.
    * The project has several eslint warnings

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Show more button should have hover state
    * Card save/trash button should have pointer cursor
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have at least two values with at least one alternative font
    * You can keep the `Inter` as alternative font, but you should also add some system fonts as alternatives, because Inter is not a system font and we need to download it to connect the font.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by Darkusmaley** [comment]
I'm not too sure what you mean by the modal form__inputs exceeding the modal window. I checked all screen sizes and the inputs  never exceed the modal window. Also based on the figma design, the modal is the same size from 1440px to 768px then it becomes smaller after that. Should It grow when upsizing from 320px?

**Comment by FiLLa-FaS** [comment]
Hey! Several small issues below are left. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Header and search form background image looks darker than it should be
    * Modal window shouldn't have external side spaces on 320 viewport
    * Incorrect width of the `modal__title`
    * Mismatches of the home page on 768px https://pasteboard.co/7OfaxKWnzXYz.png
    * Mismatches of the home page on 320px https://pasteboard.co/TJraV1iRjE3f.png
    * Incorrect width of the footer content on 320 viewport
    * Please note, that now the fonts are linked, but not all text elements have right font. You need to make sure that each element has its font according to the mockup
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages content should be centered horizontally on intermediate screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Please don't use capital letters in class names throughout the project (there's `App` class in the project)
    * BEM elements shouldn't be used outside their blocks, for example `card__list` shouldn't be used outside the `card` block. Please fix similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [ ]  There are no linting errors or warnings.
    * The project has several eslint warnings

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * All `font-family` styles should have at least two values with at least one alternative font
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 65

**Comment by FiLLa-FaS** [comment]
Hi! It's great that most of the fonts looks similar with the mockup and the eslint errors are fixed. Several small issues below are left. Good luck!✨

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Please note, that `roboto slab` font should be used in the project only in 400 font-weight, but the text looks bolder. You need to make sure that all proper font-faces files are used in the project
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages content should be centered horizontally on intermediate screen resolutions https://pasteboard.co/EuvqlisIyT0z.png
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * BEM elements shouldn't be used outside their blocks, for example `form__info` shouldn't be used outside the `form` block. Please fix similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 70

**Comment by FiLLa-FaS** [comment]
Hey! All the same issues are left, please make sure that the fixes are displayed properly. I also added additional screenshot with broken centering. Good luck!

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
    * Please note, that roboto slab font should be used in the project only in 400 font-weight, but the text still looks bolder. You need to make sure that all proper font-faces files are used in the project
- [ ]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * All pages content should be centered horizontally on intermediate screen resolutions (image was an example, you have other cases of troubles with centering https://pasteboard.co/wxYsC9swuyH3.png, please check them on all screen resolutions)
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * BEM elements shouldn't be used outside their blocks, for example `modal-form__info` shouldn't be used outside the `modal-form` block. Please fix similar cases throughout the project
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 70

**Comment by FiLLa-FaS** [comment]
Hey! You've got more than 80 points, so I'm glad to accept your project. Good luck on the next diploma stage!✨

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout or get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correct on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page, and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * BEM elements shouldn't be used outside their blocks, for example `modal-with-form__info` shouldn't be used outside the `modal-with-form` block. Please fix similar cases throughout the project. You shouldn't change the name of the BEM element class, you should use BEM elements only inside their blocks classes
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g., a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach for positioning elements has been chosen and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid` layouts are used to arrange elements whenever applicable.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 96

**Pull request merged**
